services:
  # -- -- -- -- BONUS -- -- -- --

  # -- -- -- -- cAdvisor -- -- -- --
  
  cadvisor:
    container_name: cAdvisor
    restart: on-failure
    build:
      context: ./requirements/bonus/cAdvisor/
    ports:
      - "8084:8084"
    networks:
      - wp_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  # -- -- -- -- adminer -- -- -- --
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - wp_network

  # -- -- -- -- FTP -- -- -- --
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: unless-stopped
    environment:
      FTP_USER: ftpuser
      FTP_PASS: ftppassword
    ports:
      - "21:21"
      - "30000-30010:30000-30010"
    volumes:
      - wp_site_data:/var/www/html
    networks:
      - wp_network

  # -- -- -- -- REDIS -- -- -- --
  redis:
    build: ./requirements/bonus/Redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - wp_site_data:/var/www/html
    networks:
      - wp_network
  # -- -- -- -- MARIADB -- -- -- --
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wp_db_data:/var/lib/mysql
    networks:
      - wp_network
  # # -- -- -- -- WORDPRESS -- -- -- --
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wp_site_data:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - wp_network
  # -- -- -- -- NGINX -- -- -- --
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp_site_data:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - wp_network
  # -- -- -- -- NETWORKS -- -- -- --
networks:
  wp_network:
  # -- -- -- -- VOLUMES -- -- -- --
volumes:
  wp_db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/abbouram/data/wp_db_data
      o: bind
  wp_site_data:
    driver: local
    driver_opts:
      type: none
      device: /home/abbouram/data/wp_site_data
      o: bind
