FROM alpine:3.20

RUN apk update && apk add --no-cache vsftpd lftp

COPY conf/vsftpd.conf /etc/vsftpd/vsftpd.conf
COPY tools/script.sh /script.sh

RUN chmod +x /script.sh

EXPOSE 21 21100-21110

ENTRYPOINT ["/script.sh"]