FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    vsftpd ftp \
    && rm -rf /var/lib/apt/lists/*

COPY conf/vsftpd.conf /etc/vsftpd.conf

COPY tools/script.sh /usr/local/bin/script.sh
RUN chmod +x /usr/local/bin/script.sh

EXPOSE 21

CMD ["script.sh"]