FROM debian:bookworm

# php-gd php-redis
EXPOSE 9000

RUN apt-get update && \
    apt-get install -y \
    php-fpm php-mysql \
    netcat-openbsd \
    curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sSLo /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x /usr/local/bin/wp

COPY conf/www.conf /etc/php/8.2/fpm/pool.d/www.conf
COPY --chmod=755 tools/wp_setup.sh /usr/local/bin/wp_setup.sh


ENTRYPOINT ["wp_setup.sh"]
CMD ["php-fpm8.2", "-F"]