FROM debian:bookworm

# Expose HTTPS
EXPOSE 443

# Avoid interactive prompts during apt installs
ENV DEBIAN_FRONTEND=noninteractive

# Build arguments for certificate generation
ARG CERT_FOLDER
ARG CERTIFICATE
ARG KEY
ARG COUNTRY
ARG STATE
ARG LOCALITY
ARG ORGANIZATION
ARG UNIT
ARG COMMON_NAME

# Install nginx + openssl
RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
    nginx \
    openssl \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${CERT_FOLDER} && \
    openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
    -out ${CERTIFICATE} \
    -keyout ${KEY} \
    -subj "/C=${COUNTRY}/ST=${STATE}/L=${LOCALITY}/O=${ORGANIZATION}/OU=${UNIT}/CN=${COMMON_NAME}"

# Copy nginx config
COPY conf/default.conf /etc/nginx/conf.d/default.conf

RUN  mkdir -p /var/www/html
RUN  chown -R www-data:www-data /var/www/html

# Run nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
